# Generated by Django 3.1.14 on 2023-09-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='true or not', max_length=200),
        ),
    ]
