# Generated by Django 3.1.14 on 2023-09-20 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
